### ISSUE TITLE
How to use Gource on M1 device

### ISSUE THREAD

**Issue by soulteary** [acaudwell/Gource#289] opened 2022-05-10 15:21 UTC
If anyone wants to run gource on a Macbook M1 chip device, You can refer to the following command

1. install deps

```bash
brew install pkg-config freetype2 pcre2 glow sdl2 sdl2_image boost glm autoconf
```

2. update configure

```bash
./configure --with-boost=/opt/homebrew/Cellar/boost/1.78.0_1/ CPPFLAGS="-I/opt/homebrew/Cellar/glm/0.9.9.8/include"
```

3. build gource

```bash
make
sudo make install
```

4. enjoy

The full process is documented [here](https://soulteary.com/2022/05/10/lets-talk-about-code-warehouse-visualization-with-gource.html) (translation required)

**The latest version 0.53 passed the test.**

**Comment by tbonza** [comment] 2022-10-26 00:42
@soulteary , tried the steps with OS Montery, M1, and got the following error message during configuration. Please let me know if anything comes to mind
```
...
checking whether the Boost::System library is available... yes
checking whether the Boost::Filesystem library is available... yes
configure: error: Could not link against -lGL !
```

**Comment by Yoann-Abbes** [comment] 2022-12-30 02:04
@tbonza @soulteary 
I had the same issue

I solved it with the following steps.

```bash
sudo port install libGLU
```

⚠️ If you don't have `port`, install it -> https://www.macports.org/install.php
And verify that you export `PATH` correctly in your terminal profile file (`.bashrc` or `.zshrc` or else)
```bash
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
```

And if ever, additionally, for other issues I had I installed those ones

```bash
sudo port install freetype
sudo port install giflib
sudo port install tiff
sudo port install jpeg
sudo port install libpng
sudo port install boost
sudo port install glew
sudo port install glm
sudo port install libsdl2
sudo port install libsdl2_image
sudo port install ffmpeg
```

Be patient for `ffmpeg` ;)

Then in the `configure` file, I searched for `include <GL/gl.h>` and replaced by `include <OpenGL/gl.h>` (Thanks Apple -_-)

Finally, just type
```bash
./configure
make
sudo make install
```

Enjoy

**Comment by acaudwell** [comment] 2023-01-12 00:07
I think finding GL should now be fixed on master since we recently updated the autoconf GL macros (https://github.com/acaudwell/Gource/pull/297), would be good if someone can check

**Comment by L3o-pold** [comment] 2023-01-15 10:16
@acaudwell I can confirm it's fixed on master.

**Closed** 2023-01-19 01:25 UTC
