### ISSUE TITLE
Segmentation faul: 11

### ISSUE THREAD

**Issue by gittheking** [acaudwell/Gource#53] opened 2016-02-04 01:22 UTC
Running gource in git repo is giving me a segmentation fault: 11 and quitting unexpectedly. Gource is currently located in `/usr/local/bin/gource`.

**Comment by meshy** [comment] 2016-02-04 12:41
I take it that you're running on OS X? If so, this looks like a duplicate of #51.

**Closed** 2016-02-20 03:48 UTC
